import { Metadata } from 'next';
import React from 'react';

export const metaData: Metadata = {
  title: 'next-plugin-svgr example',
  description: 'Generated by next-plugin-svgr',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
